# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ne
name: Continious Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        
      - name: Test
        run:  dotnet test -c Release --no-restore
  analysis:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: run analysis
        uses: dotnet/code-analysis@v3
        id: code-analysis
        with:
          build-breaking: true
  
