name: On Push

on:
  push

jobs:
  push-develop:
    name: Build, Test & Analyse
    if: ${{ always() && format('refs/heads/{0}', ) == github.ref }}
    uses: ./.github/workflows/build-test-analyse.yml
    secrets: inherit

  build:
    name: Build & Test
    if: ${{ always() && format('refs/heads/{0}', ) != github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore
